DefaultContentLanguage = "en"
author = "souhail chahmout"
baseURL = "https://goiw111.github.io/"
copyright = "Copyright © 2025–2025"
disqusShortname = "S.C"
enableInlineShortcodes = true
#footnoteReturnLinkContents = "^"
googleAnalytics = "GTM-NDDLWNZT" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "cn"
theme = "hugo-theme-tokiwa"
title = "My Blog"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
  bannerFont = "fonts"
  description = """
  HI, my name is Souhail and This blog is a space where I share my experiences.
  """ 
  env = "production" # for Google Analytics and DISQUS.
  favicon = "img/favicon-32x32.png" 
  fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
  math = true # for introducing $KaTeX$
  useChineseFonts = false
  postDateFormat = "2006-1-2"
  custom_css = ["css/custom.css"]

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[params.social]
github    = "https://github.com/goiw111"
linkedin  = "https://www.linkedin.com/in/souhail-chahmout"
instagram = "https://www.instagram.com/sohayl.ch"
mail      = "mailto:chahmot.s@gmail.com"


[outputs]
home = ["HTML", "RSS", "JSON"]
