# Workflow name
name: Deploy Hugo site to Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - master # Or master, or whichever branch you want to deploy from

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Needed to checkout the repository
  pages: write    # Needed to deploy to GitHub Pages
  id-token: write # Needed for OIDC token authentication

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    env:
      HUGO_VERSION: 0.145.1 # Specify your desired Hugo version (check latest)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if using submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Use action to install Hugo
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          # extended: true # Uncomment if you need the extended version (for Sass/SCSS)

      - name: Setup Pages
        id: pages # Give this step an ID to reference its outputs later
        uses: actions/configure-pages@v4

      - name: Build Hugo site
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
          # The --baseURL flag overrides your config.toml/yaml/json baseURL.
          # It ensures the site works correctly whether deployed to a root domain
          # or a subdirectory like <username>.github.io/<repository>.
          # The trailing slash is important.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'public' directory (default Hugo output)
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Get the deployment URL output
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment # Give this step an ID
        uses: actions/deploy-pages@v4 # Action to deploy the artifact to Pages
